project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Econ 149"
  favicon: "plot/econ149-hex-logo.png"
  
  repo-url: https://github.com/econ149/econ149-site
  site-url: https://econ149.github.io/econ149-site/
  
  sidebar:
    background: "#800000"
    foreground: "#ffff"
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/econ149-hex-logo.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "p1-overview-research-writing.qmd"
            text: "Overview of research writing and publications"
          - href: " "
            text: "Structuring a journal article part 1"
          - href: " "
            text: "Structuring a journal article part 2"
          - href: " "
            text: "Systematic literature review"
          - href: " "
            text: "Jounal submission: a walkthrough"


format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual

