project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "FME publication writing workshop"
  favicon: "photos/CME.png"
  
  repo-url: https://github.com/ViSERDAC-2025/fme-publication-writing
  site-url: https://viserdac-2025.github.io/fme-publication-writing
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "photos/CME.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "p1-overview-research-writing.qmd"
            text: "Overview of research writing and publications"
          - href: " "
            text: "Structuring a journal article part 1"
          - href: " "
            text: "Structuring a journal article part 2"
          - href: " "
            text: "Systematic literature review"
          - href: " "
            text: "Jounal submission: a walkthrough"


format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual

